### ISSUE TITLE
Get list of PSAS videos from Youtube

### ISSUE THREAD

**Issue by kebno** [kebno/rocket-room-display#1]

**Comment by kebno** [comment]
authenticate with PSAS account?  @natronics ?

**Comment by natronics** [comment]
https://developers.google.com/youtube/v3/docs/videos/list

Pretty much all Google API's require auth now, but not specifically from PSAS. Any developer running this code should be able to use their own developer account (for instance I should be able to clone this, add my personal google developer API key, and run it)

As far as what we'll do in production, I don't know. Maybe make a developer account with PSAS, but I'm not worried about that now.

https://developers.google.com/youtube/registering_an_application

**Comment by kebno** [comment]
OK. We'll set up something when it's finished.

For now I'm using a google account I made for this project.
